:CSname: Global Entity Reference System (GERS)
:Title: {CSname} Community Standard Work Item Justification
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <2025-mm-dd>
|Approval Date:   <2025-mm-dd>
|Internal reference number of this OGC(R) document:    25-nnnrx
|Category: OGC(R) Community Standard Work Item Justification
|Authors:   Carl Reed, PhD
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2025 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

== Introduction

This document provides a justification to the OGC Technical Committee (TC) for consideration of the Global Entiry Reference System (GERS) as a Community Standard. This justification, along with the submitted candidate Community Standard, will form the basis for TC review and vote to approve the start of a Work Item as the first step in the Community Standard process for this standard.

The submitters agree to abide by the TC Policies and Procedures and OGC Intellectual Property Rights Policy (http://www.opengeospatial.org/ogc/policies) during the processing of this submission.

Once approved, the GERS Community Standard Work Item defined by this document is valid for a period of six (6) months from the apporval date.

== Overview of proposed submission

////
Summarize the proposed Community standard. In this summary, provide an overview of the geospatial interoperability requirements the proposed standard supports, the history of its development and use, and use cases.
////

The Global Entity Reference System (GERS) was developed by the https://overturemaps.org/[Overture Maps Foundation] and launched in June 2025 as a way to provide unique, open, and interoperable identifiers for geospatial entities such as buildings, places, and road segments. This system aims to simplify data integration and sharing across different datasets and platforms, fostering collaboration and innovation in the geospatial industry

Organizations can spend up to 90% of their time and resources on data preparation and integration rather than value-adding analysis. For organizations using geospatial data, the challenge is even more acute: Different data producers describe the same real-world entities in different ways, use different reference systems, and different ontologies. Yhe combinations of these differences make it expensive and time-consuming to combine datasets from these different sources. 

Often, the cost of integrating data exceeds the cost of the initial data capture and any related licensing. This is the data conflation tax – a hidden cost that affects everyone working with data obtained from multiple sources.

GERS changes this equation by providing persistent, unique identifiers for every geospatial entity – from buildings and roads to places and addresses. With GERS, what once took weeks of complex geospatial conflation can now be accomplished in minutes with simple column joins.

== Motivation of supporting OGC Members for this submission

////
Provide a brief paragraph from one or more supporting OGC members that describes why they are supporting this submission and how they feel it helps the geospatial community.
////

== Relationship to other OGC Standards

////
State whether this proposed Community standard has any dependencies on OGC standards or is itself normatively referenced by an OGC standard and list those standards, as applicable.
////

== Alignment with OGC Standards Baseline

The GERS model and framework is based on the following international standards from the IETF, ISO, and the OGC


////
Describe where this proposed standard fits with respect to the existing OGC standards baseline and standards in development in the OGC and whether this proposed standard may compete with or enhance an existing OGC standard.
////

== Evidence of implementation

The following implementations use the proposed Community standard.

*Implementation name:*

*Date of most recent version:*

*Implementation description:*

*Implementation URL:*

*Is implementation complete?*

* [x] Yes
* [ ] No

*If not,* what portions of the proposed Community standard are implemented?

////
Repeat for each implementation. Place a "x" in the appropriate box regarding complete implementation.
Optionally, provide a narrative description of the extent of implementation of the proposed Community standard for those proposed standards that are very widely used.
////

== Information on adoption

////
Describe the breadth of adoption of the proposed Community Standard. For example, are the implementations widely used in the geospatial community or subsets of the community? Are implementations limited, but used by most organizations that need the capabilities of the proposed Community Standard? Does the proposed Community Standard serve an emerging part of the geospatial community?
////

== Public availability

Is the proposed Community standard currently publicly available?

* [x] Yes
* [ ] No

URL:

== Supporting OGC Members

////
List the supporting organizations. There must be at least three OGC organizations of which at least one must be an OGC Voting Member.
////

== Intellectual Property Rights

Will the contributor retain intellectual property rights?

* [ ] Yes
* [ ] No

If yes, the contributor will be required to work with OGC staff to properly attribute the submitter’s intellectual property rights.

If no, the contributor will assign intellectual property rights to the OGC.
