:CSname: Global Entity Reference System (GERS)
:Title: {CSname} Community Standard Work Item Justification
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <2025-mm-dd>
|Approval Date:   <2025-mm-dd>
|Internal reference number of this OGC(R) document:    25-024
|Category: OGC(R) Community Standard Work Item Justification
|Authors:   Carl Reed, PhD
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2025 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

== Introduction

This document provides a justification to the OGC Technical Committee (TC) for consideration of the Global Entiry Reference System (GERS) as a Community Standard. This justification, along with the submitted candidate Community Standard, will form the basis for TC review and vote to approve the start of a Work Item as the first step in the Community Standard process for this standard.

The submitters agree to abide by the TC Policies and Procedures and OGC Intellectual Property Rights Policy (http://www.opengeospatial.org/ogc/policies) during the processing of this submission.

Once approved, the GERS Community Standard Work Item defined by this document is valid for a period of six (6) months from the apporval date.

More information on the Overture Maps GERS information can be found here: https://overturemaps.org/blog/2025/understanding-overtures-global-entity-reference-system/

== Overview of proposed submission

This section provides an overview of the proposed submission, benefits of implementing GERS, a summary of the GERS Model, and an overview of the organization submitting this Community Standard: Overture Maps Foundation.

=== Overview of the GERS Model and Reference System

The Global Entity Reference System (GERS) was developed by the https://overturemaps.org/[Overture Maps Foundation] and launched in June 2025 as a way to provide unique, open, and interoperable identifiers for geospatial entities such as buildings, places, and road segments. This system aims to simplify data integration and sharing across different datasets and platforms, fostering collaboration and innovation in the geospatial industry

Organizations can spend amount of time and resources on data preparation and integration rather than value-adding analysis. For organizations using geospatial data, the challenge is even more acute: Different data producers describe the same real-world entities in different ways, use different reference systems, and different ontologies. The combinations of these differences make it expensive and time-consuming to combine datasets from these different sources. 

Often, the cost of integrating data exceeds the cost of the initial data capture and any related licensing. This is the data conflation tax – a hidden cost that affects everyone working with data obtained from multiple sources.

GERS changes this equation by providing persistent, unique identifiers for every geospatial entity – from buildings and roads to places and addresses. With GERS, what once took weeks of complex geospatial conflation can now be accomplished in minutes with simple column joins.

=== What will be standardized?

Overture provides a complete and operational implementation of the GERS Model that includes data schemas, a registry schema, the GERS ID generation, processes, tools, and the physical foundation reference amp that is maintained by the Overture Map Foundation. The proposed OGC GERS Community Standard has a more limited focus that includes the model as documented in the data and registry schema, and the generation of the GERS ID. This focus results in a  standard that can be implemented by any organization that will be 100% consistent with the existing Overture foundation map but "owned" by the implementing organization. An example of this approach is the precisely implementation (See below).

=== Benefits of implementing GERS

The key benefits of implementing GERS as identified by the Overture Foundation community are:

- Simplified Data Integration: GERS IDs allow developers to easily link datasets by joining columns rather than relying on complex data conflation processes, saving time and resources. 
- Reduced Costs: By streamlining data integration, GERS helps reduce the "hidden tax" of data integration, making it more cost-effective to incorporate new data into mapping solutions. 
- Increased Interoperability: GERS promotes interoperability by providing a common language for identifying geospatial entities, enabling data sharing and collaboration between different organizations and platforms. 
- Enhanced Data Richness: With GERS, it becomes easier to enrich map data with information from various sources, leading to more comprehensive and informative mapping applications. 
- Innovation in Geospatial: GERS is expected to drive innovation in the geospatial industry by reducing barriers to data integration and enabling the development of new and more powerful mapping solutions. 

=== What is the Overture Maps Foundation"

Overture is a collaborative open-data initiative led by software developers, data experts, cartographic engineers, and product managers from dozens of Overture Maps Foundation member companies. Since its launch in December 2022, Overture members have been working toward a shared vision: To create reliable, user-friendly, and interoperable open map data that supports both current and future map products. Overture Members envision a world where shared, open base layers drive collaboration and innovation across industries and communities.

To achieve this, Overture’s core contributors have been developing our common schema, datasets, platform, and system of unique, stable IDs known as GERS. Member companies contribute data and engineering expertise to enable the creation of global datasets that are accurate, comprehensive, and regularly updated to reflect changes in the world. By combining multiple data sources and fostering cross-company collaboration, we are able to achieve results no single organization could accomplish alone.

NOTE: Many of the Overture Foundation members are also OGC Members, including: Esri, TomTom, con terra GmbH, Maxar, and CampToCamp. A number of past OGC Member organizations are also key supporters of the Overture Maps foundation, inluding AWS and Microsoft.

== Motivation of supporting OGC Members for this submission

////
Provide a brief paragraph from one or more supporting OGC members that describes why they are supporting this submission and how they feel it helps the geospatial community.
////

== Alignment with OGC and other International Standards

The GERS model and framework is based on the following international standards from the IETF, ISO, and the OGC including:

- The GERS ID is generated following the rules as defined in IETF https://datatracker.ietf.org/doc/html/rfc4122[RFC 4122] A Universally Unique IDentifier (UUID) URN Namespace.
- The GERS geometry model is consistent with https://www.iso.org/standard/26012.html[ISO 19107] as instantiated by the recommended use of GeoJSON as the encoding format for geometry in the GERS reference map data store.
- https://json-schema.org/[JSON Schema] is used for defining all GERS schema including the ID registry and the structure of the foundation maps in the GERS reference map data store.
- https://github.com/opengeospatial/geoparquet[GeoParquet] is the recommended distribution format for geospatial content contained in the reference map data store.

NOTE: A GERS referance map data store is a set of validated datasets that connect GERS IDs to real-world entities. The Overture GERS implementation provides a reference map with monthly open map data updaetes. These data updates are carefully validated, consistently structured collections that describe billions of real-world entities. Each entity in these datasets carries a unique GERS ID. These IDs represent actual physical entities in the world.

NOTE: Overture Maps Foundation provides global data across six data themes (addresses, base, buildings, divisions, places, and transportation), using well-partitioned GeoParquet as their primary distribution format across multiple clouds. This referebce map consists of billions of features across hundreds of gigabytes. 

=== Relationship to OGC Points of Interest (PoI) Conceptual Model Standard

The OGC docs.ogc.org/is/21-049/21-049.html[Points of Interest] (POI) Conceptual Model is an open data model for representing information about POI. 
A POI can be as simple as a set of coordinates and an identifier. The model specifically states that "An encoding of the AbstractFeature class SHALL 
include zero or one identifier attributes" (Requirement 6) and that if an identifier is specified that the identifier of the feature is unique and valid globally.

NOTE: From PoI Standard - Abstract Feature class in POI model: identifer «property»	ScopedName [0..*]	Specifies the unique identifier of the feature that is valid globally.

Further, the geometry model specified in the GERS Model is consistent with the PoI geometry model (/req/core/geometry):

-The POI Conceptual Model spatial geometry properties SHALL be compliant with the Geometry Model defined in ISO 19107
- The spatial geometry properties of all POI instances SHALL be defined using one or more of the following classes: GM_Point, GM_LineString, GM_Polygon

=== Relationship to existing OGC standards baseline and standards in development in the OGC

The proposed GERS Community Standard does not conflict with or overlap functionalty defined in the current OGC Standards baseline or new standards being developed.
The GERS Model and implementations build on the existing OGC/ISO Standards baseline. Further, implementations of various OGC API Standards could be used to access
a GERS reference map data store.

== Evidence of implementation

=== Overview of implementations

The following implementations use the proposed Community Standard.

Organizations that support and rely on Overture data, and therefore are effectively "implementing" or leveraging GERS, include:

- Amazon Web Services (AWS)
- Meta
- Microsoft
- TomTom
- Esri
- Precisely (using GERS IDs to integrate with their data products)
- Addresscloud (leveraging GERS for geospatial risk analysis)

=== *Precisely Data Link Program:*

*Date of most recent version:*

June 2025

*Implementation description:*

Precisely, a global leader in data integrity with over 12,000 customers, including 93 of the Fortune 100, has integrated Overture Maps’ Global Entity Reference System (GERS) into their https://www.precisely.com/solution/data-link?utm_source=Overture&utm_medium=Case+Study&utm_id=GERS[Data Link program]. Data Link streamlines integrating datasets from multiple providers by connecting data from Precisely and other organizations via unique identifier systems. The connection Data Link establishes between GERS and Precisely’s unique IDs dramatically reduces the time and cost of integrating Overture Maps’ standardized and interoperable datasets with Precisely’s comprehensive data portfolio spanning properties, locations, markets, and more.

Precisely solutions leverage their broader ID system and the PreciselyID, a unique and persistent identifier assigned to addresses through validation and geocoding services. By creating link tables between GERS IDs and Precisely’s unique IDs, they’ve eliminated the need for complex spatial operations.

*Implementation URL:*

https://www.precisely.com/solution/data-link?utm_source=Overture&utm_medium=Case+Study&utm_id=GERS

*Is implementation complete?*

* [x] Yes

////
Repeat for each implementation. Place a "x" in the appropriate box regarding complete implementation.
Optionally, provide a narrative description of the extent of implementation of the proposed Community standard for those proposed standards that are very widely used.
////

== Information on adoption

////
Describe the breadth of adoption of the proposed Community Standard. For example, are the implementations widely used in the geospatial community or subsets of the community? Are implementations limited, but used by most organizations that need the capabilities of the proposed Community Standard? Does the proposed Community Standard serve an emerging part of the geospatial community?
////

== Public availability

Is the proposed Community standard currently publicly available?

* [x] Yes
* [ ] No

URL: https://github.com/OvertureMaps

== Supporting OGC Members

The following OGC Members suppot this submission:

|===
| Organization | Member Level | URL
| Overture Maps| Principal    |
|===

== Intellectual Property Rights

Will the contributor retain intellectual property rights?

* [X] Yes
* [ ] No



Overture Maps

The companies listed above have granted the Open Geospatial Consortium (OGC) a nonexclusive, royalty-free, paid up, worldwide license to copy and distribute this document and to modify this document and distribute copies of the modified version under a <<TBD>> license (see below).
