:CSname: Global Entity Reference System (GERS) Framework
:Title: {CSname} Community Standard Work Item Justification
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <2025-10-28>
|Approval Date:   <2025-mm-dd>
|Internal reference number of this OGC(R) document:    25-024
|Category: OGC(R) Community Standard Work Item Justification
|Authors:   Carl Reed, PhD
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2025 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

== Introduction

This document provides a justification to the OGC Technical Committee (TC) for consideration of the Global Entity Reference System (GERS) framework as an OGC Community Standard. This justification, along with the submitted candidate Community Standard, will form the basis for TC review and vote to approve the start of a Work Item as the first step in the Community Standard process for this standard.

The submitters agree to abide by the TC Policies and Procedures and OGC http://www.opengeospatial.org/ogc/policies[Intellectual Property Rights Policy] during the processing of this submission.

Once approved, the GERS Community Standard Work Item defined by this document is valid for a period of six (6) months from the approval date.

More information on the Overture Maps GERS framework can be found here: https://overturemaps.org/blog/2025/understanding-overtures-global-entity-reference-system/

== Overview of proposed submission

This section provides an overview of the proposed submission, benefits of implementing GERS, a summary of the GERS Model, and an overview of the organization submitting this Community Standard: Overture Maps Foundation.

The Global Entity Reference System (GERS) was developed by the https://overturemaps.org/[Overture Maps Foundation]. The latest version launched in June 2025 as a way to provide unique, open, and interoperable identifiers for geospatial entities such as buildings, places, and road segments. This system aims to simplify data integration and sharing across different datasets and platforms, fostering collaboration and innovation in the geospatial industry

Overture provides a complete and operational implementation of the GERS Model that includes data schemas, a registry schema, the GERS ID generation, processes, tools, and the physical foundation reference map maintained by the Overture Map Foundation. 

The proposed OGC GERS Community Standard will have a more limited focus the logical model for a GERS framework as documented in the current Overture data, bridge, change log, reference map, and registry schema. This focus defines a standard that can be implemented by any organization that will be 100% consistent with the existing Overture Maps Foundation reference map and IDs but "owned" by the implementing organization.

=== Overview of the GERS Model and Reference System

Organizations can spend amount of time and resources on data preparation and integration rather than value-adding analysis. For organizations using geospatial data, the challenge is even more acute: Different data producers describe the same real-world entities in different ways, use different reference systems, and different ontologies. The combinations of these differences make it expensive and time-consuming to combine datasets from these different sources. 

Often, the cost of integrating data exceeds the cost of the initial data capture and any related licensing. This is the data conflation tax – a hidden cost that affects everyone working with data obtained from multiple sources.

GERS changes this equation by providing persistent, unique identifiers for every geospatial entity – from buildings and roads to places and addresses. With GERS, what once took weeks of complex geospatial conflation can now be accomplished in minutes with simple column joins.

=== What will be standardized?

The following components of the Global Entity Reference System will be addressed in the GERS Community Standard. The source of the content for the draft Community Standard is the July 2025 of the Overture GERS release.

- BridgeFiles: Bridge files connect the unique GERS IDs to the features identifiers used in the source data. These files are a key component of GERS and 
offer two critical capabilities: reverse lookup of source features and the ability to join content from multipoe geospatial data repositories.
- ChangeLog: A GERS changelog capture changes in the map data from the previous release to the current release. This information can be used to 
guide decisions about data matching, better understand data stability, and help detect data errors.
- GERS ID: A GERS ID is a unique identifier for real-world geospatial entities across data releases and maintains consistency when the same entity appears in multiple source datasets.
- ReferenceMap: A reference map of all entities that have been assigned a unique GERS ID. The content in the reference map is defined by a set of JSON schema.
- Registry: A GERS Registry serves as the single source of truth for all entities that are part of an implementation of a Global Entity Reference System.
- JSON Schema: The format of the content stored in the reference map is defined using JSON schema. Overture releases their reference map data as GeoParquet. 
GeoJSON is used as the default canonical geospatial format. GeoJSON provides a "mental model and language" to express data constructions in the schema. 
The OGC GERS Standard schema reference docs will describe key schema concepts for each theme and definitions and examples for each feature type.
- Feature Types: The source Overture JSON schema provide type enumerations for the base themes, such as land cover types. The OGC GERS Standard will 
define how an enumeration contained in the schema can be extended while maintaining backwards compatibility.

Each of the above components are defined using JSON Schema that will clearly and fully documented in the OGC GERS Community Standard. 

=== What will not be in the Community Standard

No Overture maintained data, registry content, maps, tools, or workflow processes will be part of the OGC Community Standard.

=== Benefits of implementing a GERS Framework

The key benefits of implementing a GERS framework as identified by the Overture Foundation community are as follow.

- Simplified Data Integration: GERS IDs allow developers to easily link datasets by joining columns rather than relying on complex data conflation processes, saving time and resources. 
- Reduced Costs: By streamlining data integration, GERS helps reduce the "hidden tax" of data integration, making it more cost-effective to incorporate new data into mapping solutions. 
- Increased Interoperability: GERS promotes interoperability by providing a common language for identifying geospatial entities, enabling data sharing and collaboration between different organizations and platforms. 
- Enhanced Data Richness: With GERS, it becomes easier to enrich map data with information from various sources, leading to more comprehensive and informative mapping applications. 
- Innovation in Geospatial: GERS is expected to drive innovation in the geospatial industry by reducing barriers to data integration and enabling the development of new and more powerful mapping solutions. 

=== GERS Value Proposition - Summary

Key value points include the following.

- Data integration: Simplifies the exchange and integration of map data by using a universal system of consistent identifiers (GERS IDs) for entities.
- Reliability: Provides persistent IDs and changelogs for geospatial entities, improving data traceability, auditability, and accuracy.
- Accessibility: As a free and open backbone, GERS provides a no-cost path to global identifiers and prevents vendor lock-in.
- AI and data pipelines: Offers persistent identifiers that help ground facts to real-world assets, which is crucial for training and operating accurate AI system. 

== Motivation of supporting OGC Members for this submission

////
Provide a brief paragraph from one or more supporting OGC members that describes why they are supporting this submission and how they feel it helps the geospatial community.
////

== Alignment with OGC and other International Standards

=== Alignment with Non OGC International Standards

The GERS model and framework is based on the following international standards from the IETF, ISO, and the OGC including:

- The GERS ID is generated following the rules as defined in IETF https://datatracker.ietf.org/doc/html/rfc4122[RFC 4122] A Universally Unique IDentifier (UUID) URN Namespace.
- The GERS geometry model is consistent with https://www.iso.org/standard/26012.html[ISO 19107] as instantiated by the recommended use of GeoJSON as the encoding format for geometry in the GERS reference map data store.
- https://json-schema.org/[JSON Schema] is used for defining all GERS schema including the ID registry and the structure of the foundation maps in the GERS reference map data store.
- https://github.com/opengeospatial/geoparquet[GeoParquet] is the recommended distribution format for geospatial content contained in the reference map data store.

NOTE: A GERS reference map is a set of validated datasets that connect GERS IDs to real-world entities. The Overture GERS implementation provides a reference map with monthly open map data updates. These data updates are carefully validated, consistently structured collections that describe billions of real-world entities. Each entity in these datasets carries a unique GERS ID. These IDs represent actual physical entities in the world.

NOTE: Overture Maps Foundation provides global data across six data themes (addresses, base, buildings, divisions, places, and transportation), using well-partitioned GeoParquet as their primary distribution format across multiple clouds. This reference map consists of billions of features across hundreds of gigabytes. 

===  Alignment with OGC Standards baseline

==== Relationship to OGC Points of Interest (PoI) Conceptual Model Standard

The OGC docs.ogc.org/is/21-049/21-049.html[Points of Interest] (POI) Conceptual Model is an open data model for representing information about POI. 
A POI can be as simple as a set of coordinates and an identifier. The model specifically states that "An encoding of the AbstractFeature class SHALL include zero or one identifier attributes" (Requirement 6) and that if an identifier is specified that the identifier of the feature is unique and valid globally.

NOTE: From PoI Standard - Abstract Feature class in POI model: identifier «property»	ScopedName [0..*]	Specifies the unique identifier of the feature that is valid globally.

Further, the geometry model specified in the GERS Model is consistent with the PoI geometry model (/req/core/geometry):

-The POI Conceptual Model spatial geometry properties SHALL be compliant with the Geometry Model defined in ISO 19107
- The spatial geometry properties of all POI instances SHALL be defined using one or more of the following classes: GM_Point, GM_LineString, GM_Polygon.

==== Relationship to OGC CDB 2.0 Standard

The CDB User Community has, for years, asked for better indexing and discovery capabilities as part of a CDB structured datastore. Implementing components for the GERS Framework, such as a Registry, Change Log, and Bridge files. Further, having a unique ID for every entity in a CDB datastore would 1.) support cross LoD feature joins, 2.) enable easier and searchable change history (versioning), and 3.) enable joins with non-CDB geospatial repositories - such as the Overture Maps GERS members map contributions.

==== Relationship to OGC API Standards

An OGC API Records endpoint could being uses to access and maintain a GERS Registry instance.

An OGC API Features endpoint could being uses to search, access and maintain a GERS reference map. GeoJSON is the default GERS format for exchange of geospatial content.

=== Relationship to existing OGC standards baseline and standards summary

The proposed GERS Community Standard does not conflict with or overlap functionality defined in the current OGC Standards baseline or new standards being developed.

The GERS Model and implementations build on the existing OGC/ISO Standards baseline. Further, implementations of various OGC API Standards could be used to access a GERS reference map data store.

== Evidence of implementation

=== Overview of implementations

Organizations that support and rely on Overture data, and therefore are effectively "implementing" or leveraging GERS, include:

- Amazon Web Services (AWS)
- Meta
- Microsoft
- TomTom
- Esri
- Precisely (using GERS IDs to integrate with their data products)
- Addresscloud (leveraging GERS for geospatial risk analysis)

Specifically, the following applications implement the proposed GERS Community Standard.

=== Overture Maps Foundation

*Date of most recent version:*

June 2025

*Implementation description:*

The Global Entity Reference System (GERS) is a universal framework for structuring and matching map data across systems. GERS, coupled with Overture datasets, is a potential standard for identifying and referencing the physical and conceptual entities we've defined in our world. It is also a mechanism that can simplify the integration and exchange of data layers.

GERS provides stable identifiers called GERS IDs for real-world geospatial entities across data releases and maintains consistency when entities appear in multiple source datasets.

*Implementation URL:*

https://overturemaps.org/gers/

*Is implementation complete?*

* [x] Yes

=== *Precisely Data Link Program:*

*Date of most recent version:*

June 2025

*Implementation description:*

Precisely, a global leader in data integrity with over 12,000 customers, including 93 of the Fortune 100, has integrated Overture Maps’ Global Entity Reference System (GERS) into their https://www.precisely.com/solution/data-link?utm_source=Overture&utm_medium=Case+Study&utm_id=GERS[Data Link program]. Data Link streamlines integrating datasets from multiple providers by connecting data from Precisely and other organizations via unique identifier systems. The connection Data Link establishes between GERS and Precisely’s unique IDs dramatically reduces the time and cost of integrating Overture Maps’ standardized and interoperable datasets with Precisely’s comprehensive data portfolio spanning properties, locations, markets, and more.

Precisely solutions leverage their broader ID system and the PreciselyID, a unique and persistent identifier assigned to addresses through validation and geocoding services. By creating link tables between GERS IDs and Precisely’s unique IDs, they’ve eliminated the need for complex spatial operations.

*Implementation URL:*

https://www.precisely.com/solution/data-link?utm_source=Overture&utm_medium=Case+Study&utm_id=GERS

*Is implementation complete?*

* [x] Yes

=== inHotel: Global Property IDs for Hospitality and Travel

*Date of most recent version:*

Spring 2025

*Implementation description:*

Aligned with our mission to support people in travel and hospitality through AI, we provide a GERS management service for hotels, hostels, restaurants, cafes, bars, car rental stations, golf courses, spas, tour operators and other venues. We help companies discover their GERS ID, map and verify property records, maintain authoritative metadata, associate AI agent endpoints and manage change so partners and AI agents can join reliably. We do this because geospatial grounding is essential for AI agents to truly represent a property, anchor answers to the correct location and preserve authoritative context for transactions and recommendations.

*Implementation URL:*

https://www.inhotel.io/docs/gers-global-property-ids-for-hospitality-and-travel/

*Is implementation complete?*

* [x] Yes

== Public availability

Is the proposed Community standard currently publicly available?

* [x] Yes
* [ ] No

URL: https://github.com/OvertureMaps

== Supporting OGC Members

The following OGC Members support this submission:

|===
|Name |Organization| Membership Level
| Amy Rose |Overture Maps| Principal    
| Carl Reed | Carl Reed & Associates | Individual
| Deane Kensok | Esri | Principal
|===

== Intellectual Property Rights

Will the contributor retain intellectual property rights?

* [X] Yes
* [ ] No

Overture Maps

The companies listed above have granted the Open Geospatial Consortium (OGC) a nonexclusive, royalty-free, paid up, worldwide license to copy and distribute this document and to modify this document and distribute copies of the modified version under a <<TBD>> license (see below).

=== Additional Information: What is the Overture Maps Foundation"

Overture is a collaborative open-data initiative led by software developers, data experts, cartographic engineers, and product managers from dozens of Overture Maps Foundation member companies. Since its launch in December 2022, Overture members have been working toward a shared vision: To create reliable, user-friendly, and interoperable open map data that supports both current and future map products. Overture Members envision a world where shared, open base layers drive collaboration and innovation across industries and communities.

To achieve this, Overture’s core contributors have been developing common schema, datasets, platform, and system of unique, stable IDs known as GERS. Member companies contribute data and engineering expertise to enable the creation of global datasets that are accurate, comprehensive, and regularly updated to reflect changes in the world. By combining multiple data sources and fostering cross-company collaboration, we are able to achieve results no single organization could accomplish alone.

NOTE: Many of the Overture Foundation members are also OGC Members, including: Esri, TomTom, con terra GmbH, Maxar, and CampToCamp. A number of past OGC Member organizations are also key supporters of the Overture Maps foundation, inluding AWS and Microsoft.

