:CSname: Global Entity Reference System (GERS)
:Title: Draft {CSname} SWG Charter
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <2025-mm-dd>
|Approval Date:   <2025-mm-dd>
|Internal reference number of this OGC(R) document:    25-024
|Category: OGC(R) Standards Working Group Charter
|Authors:   Carl Reed, PhD
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2025 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

To: OGC members & interested parties

A new OGC Standards Working Group is being formed. The OGC members listed below have proposed the OGC <Name of SWG>.  The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures.

The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG's official charter. Technical discussions may occur no sooner than the SWG's first meeting.

This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG at the first meeting (see details below) are that:

* You must be an employee of an OGC member organization or an individual
member of OGC;

* The OGC member must have signed the OGC Membership agreement;

* You must notify the SWG chair of your intent to participate to the first meeting. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

* You must attend meetings of the SWG. The first meeting of this SWG is at the time and date fixed below. Attendance may be by teleconference.

Of course, participants also may join the SWG at any time. The OGC and the SWG welcomes all interested parties.

Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.

Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

== Purpose of the Standards Working Group

The purpose of the Global Entity Reference System (GERS) Standards Working Group is to write a draft GERS Standard and move this document through the OGC RFC Process to become 
an official OGC adopted Standard. The work of the SWG will be based on the existing, operational https://overturemaps.org/blog/2025/understanding-overtures-global-entity-reference-system/[Overture Maps GERS Framework]. 

GERS was developed by the https://overturemaps.org/[Overture Maps Foundation] and launched in June 2025 as a way to provide unique, open, 
and interoperable identifiers for geospatial entities such as buildings, places, and road segments. The GERS framework also provides schema and a framework
to register and maintain a persistent registry of these unique IDs. This includes a change log so that changes to
geographic entities over time can be captured and persisted. This system aims to simplify data integration and sharing across different 
datasets and platforms, fostering collaboration and innovation in the geospatial industry.

Overture provides a complete and operational implementation of the GERS Model that includes data schemas, a registry schema, the GERS ID generation, processes, 
tools, and the physical foundation reference map maintained by the Overture Map Foundation. The proposed OGC GERS Standard will have a more limited focus 
that includes the model as documented in the current Overture data and registry schema, and the generation of the GERS ID. This focus results in a standard that can be implemented 
by any organization that will be 100% consistent with the existing Overture foundation map but "owned" by the implementing organization. An example of this 
approach is the `precisely` implementation (See Annex A).

== Business value proposition

The following is a value statement from the community focused on https://www.inhotel.io/[AI-augmented hospitality future].

GERS provides a free, open backbone for identifiers and <map data> joining that any vendor or hotel can use. That means hotels and vendors have a no-cost path to global identifiers and can choose to build domain services on top of it without mandatory subscription lock-in to an industry-only identifier. The economic choice is significant: choose open commons plus optional value-added services, not forced dependency.

=== Overview

Organizations can spend a tremendous amount of time and resources on geospatial data preparation and integration rather than focusing resources on value-adding analysis. For organizations using geospatial data, 
the challenge is even more acute: Different data producers describe the same real-world entities in different ways, use different reference systems, and different 
ontologies. The combinations of these differences make it expensive and time-consuming to combine datasets from these different sources. 

Often, the cost of integrating data exceeds the cost of the initial data capture and any related licensing. This is the data conflation tax – a hidden cost 
that affects everyone working with data obtained from multiple sources.

GERS changes this equation by providing persistent, unique identifiers for every geospatial entity – from buildings and roads to places and addresses. 
With GERS, what once took weeks of complex geospatial conflation can now be accomplished in minutes with simple column joins.

=== Key Benefits of implementing GERS

The key benefits of implementing GERS as identified by the Overture Foundation community are:

- Simplified Data Integration: GERS IDs allow developers to easily link datasets by joining columns rather than relying on complex data conflation processes, saving time and resources. 
- Reduced Costs: By streamlining data integration, GERS helps reduce the "hidden tax" of data integration, making it more cost-effective to incorporate new data into mapping solutions. 
- Increased Interoperability: GERS promotes interoperability by providing a common language for identifying geospatial entities, enabling data sharing and collaboration between different organizations and platforms. 
- Enhanced Data Richness: With GERS, it becomes easier to enrich map data with information from various sources, leading to more comprehensive and informative mapping applications. 
- Innovation in Geospatial: GERS is expected to drive innovation in the geospatial industry by reducing barriers to data integration and enabling the development of new and more powerful mapping solutions. 

=== GERS Value Proposition - Summary

Key value points:

- Data integration: Simplifies the exchange and integration of map data by using a universal system of consistent identifiers (GERS IDs) for entities.
- Reliability: Provides persistent IDs and changelogs for geospatial entities, improving data traceability, auditability, and accuracy.
- Accessibility: As a free and open backbone, GERS provides a no-cost path to global identifiers and prevents vendor lock-in.
- AI and data pipelines: Offers persistent identifiers that help ground facts to real-world assets, which is crucial for training and operating accurate AI system.

== Scope of work

The following components of the Global Entity Reference System will be addressed by the GERS SWG. These components will be documented in 
the draft OGC GERS Standard. The source of the content for the draft is the July 2025 of the Overture GERS release.

- BridgeFiles: Bridge files connect the unique GERS IDs to the features identifiers used in the source data. These files are a key component of GERS and 
offer two critical capabilities: reverse lookup of source features and the ability to join content from multipoe geospatial data repositories.
- ChangeLog: A GERS changelog capture changes in the map data from the previous release to the current release. This information can be used to 
guide decisions about data matching, better understand data stability, and help detect data errors.
- GERS ID: A GERS ID is a unique identifier for real-world geospatial entities across data releases and maintains consistency when the same entity appears in multiple source datasets.
- ReferenceMap: A reference map of all entities that have been assigned a unique GERS ID. The content in the reference map is defined by a set of JSON schema.
- Registry: A GERS Registry serves as the single source of truth for all entities that are part of an implementation of a Global Entity Reference System.
- JSON Schema: The format of the content stored in the reference map is defined using JSON schema. Overture releases their reference map data as GeoParquet. 
GeoJSON is used as the default canonical geospatial format. GeoJSON provides a "mental model and language" to express data constructions in the schema. 
The OGC GERS Standard schema reference docs will describe key schema concepts for each theme and definitions and examples for each feature type.
- Feature Types: The source Overture JSON schema provide type enumerations for the base themes, such as land cover types. The OGC GERS Standard will 
define how an enumeration contained in the schema can be extended while maintaining backwards compatibility.

Each of the above components are defined using JSON Schema that will clearly and fully documented in the draft OGC GERS Standard. 

=== Statement of relationship of planned work to the current OGC Standards baseline

The GERS model and framework is based on the following international standards from the IETF, ISO, and the OGC including:

- The GERS ID is generated following the rules as defined in IETF https://datatracker.ietf.org/doc/html/rfc4122[RFC 4122] A Universally Unique IDentifier (UUID) URN Namespace.
- The GERS geometry model is consistent with https://www.iso.org/standard/26012.html[ISO 19107] as instantiated by the recommended use of GeoJSON as the encoding format for geometry in the GERS reference map data store.
- https://json-schema.org/[JSON Schema] is used for defining all GERS schema including the ID registry and the structure of the foundation maps in the GERS reference map data store.
- https://github.com/opengeospatial/geoparquet[GeoParquet] is the recommended distribution format for geospatial content contained in the reference map data store.

NOTE: A GERS reference map data store is a set of validated datasets that connect GERS IDs to real-world entities. 
The Overture GERS implementation provides a reference map with monthly open map data updates. These data updates are 
carefully validated, consistently structured collections that describe billions of real-world entities. Each entity in 
these datasets carries a unique GERS ID. These IDs represent actual physical entities in the world.

NOTE: Overture Maps Foundation provides global data across six data themes (addresses, base, buildings, divisions, places, 
and transportation), using well-partitioned GeoParquet as their primary distribution format across multiple clouds. This 
reference map consists of billions of features across hundreds of gigabytes. 

=== Relationship to specific OGC Standards and on-going work

==== OGC Points of Interest (PoI) Conceptual Model Standard

The OGC docs.ogc.org/is/21-049/21-049.html[Points of Interest] (POI) Conceptual Model is an open data model for representing information about POI. 
A POI can be as simple as a set of coordinates and an identifier. The model specifically states that "An encoding of the AbstractFeature class SHALL 
include zero or one identifier attributes" (Requirement 6) and that if an identifier is specified that the identifier of the feature is unique and valid globally.

NOTE: From PoI Standard - Abstract Feature class in POI model: identifer «property»	ScopedName [0..*]	Specifies the unique identifier of the feature that is valid globally.

Further, the geometry model specified in the GERS Model is consistent with the PoI geometry model (/req/core/geometry):

-The POI Conceptual Model spatial geometry properties SHALL be compliant with the Geometry Model defined in ISO 19107
- The spatial geometry properties of all POI instances SHALL be defined using one or more of the following classes: GM_Point, GM_LineString, GM_Polygon

The PoI SWG was briefed on the proposed GERS SWG activity in August 2025.

==== OGC CDB 2.0 Standard

The CDB Version 2.0: Core Standard specifies requirements (rules) defining a standardized model and structure for a single, versionable, virtual representation of the earth. Conceptually, the GERS model and the CDB model are very similar. As such, key elements of the GERS framework such as the generation of unique IDs and the Registry easily fit the CDB model. Further, incorporation of these elements would increase the utility and useability of implementations of the CDB Standard.

The CDB 2.0 SWG was briefed on the planned GERS SWG activity September 25, 2025.

== Additional characteristics of the GERS SWG

=== Relationship to existing OGC standards baseline and standards in development in the OGC

The proposed GERS Community Standard does not conflict with or overlap functionality defined in the current OGC Standards baseline or new standards being developed.
The GERS Model and implementations build on the existing OGC/ISO Standards baseline. Further, implementations of various OGC API Standards could be used to access
a GERS reference map data store. The CDB Standard could include a GERS requirements class that would define how a CDB Profile to incorporate unique identifiers for features in a CDB datastore.

=== What is out of scope?

The SWG will not extend the GERS framework beyond the capabilities and functions defined in the initial submission of GERS by the Overture Maps Foundation to the OGC.
Further, the SWG will not consider or standardize the current content in the Overture Maps datastore, the Overture processing tools, or any other implementation specific technology.

=== Specific existing work used as starting point

The GERS SWG will use the GERS framework, model, and schema as defined, in general, https://overturemaps.org/blog/2025/understanding-overtures-global-entity-reference-system/[here].

=== Is this a persistent SWG

[X] NO

=== When can the SWG be inactivated

When the OGC GERS candidate standards is approved by the TC and the PC as an adopted OGC Standard.

=== Description of deliverables

An OGC Global Entity Reference System Implementation Standard including relevant JSON schema. 

NOTE: User support materials are already available on the Overture Maps web site.

=== Initial deliverables

The initial deliverable will be a candidate OGC Global Entity Reference System Implementation Standard. 

=== Additional SWG tasks

Not applicable

=== IPR Policy for this SWG

[x] RAND-Royalty Free

=== Anticipated audience / participants

The target audience for a GERS Standard are the developers, companies, and organizations that build or use geospatial data and applications that require geospatial content from 
multiple datastores to be "joined" (fused). Participants in the SWG activity would be any member that has digital twin, modelling, simulation, analytics, or AI training application requirements.


== Domain Working Group endorsement

The OGC Points of Interest SWG has been briefed on this work. 

== Other informative information about the work of this SWG

=== Collaboration

Overture Maps Foundation is a https://jointdevelopment.org/[Joint Development Foundation Project], an affiliate of the Linux Foundation. They are an OGC Principal Member

=== Details of first meeting

The first ad-hoc meeting of the SWG will be held at the Boulder Meetings, October 2025. Once the charter is approved, participation information will be provided to the 
SWG's e-mail list and on the Agora calendar in advance of the meeting. During the first meeting, the SWG Chair and co-chair will be nominated and voted on. The other 
primary work item will be defining a timeline and work agenda.

=== Projected on-going meeting schedule

The work of the SWG will be carried out primarily by email and conference calls, possibly every two weeks, with face-to-face meetings perhaps at each of the OGC TC meetings. All content for the GERS standard will be maintained on an https://github.com/opengeospatial/Overture-Maps-GERS/tree/main[OGC Git repository]. 

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page. 

|===
|Name |Organization| Membership Level
| Amy Rose |Overture Maps| Principal    
| Carl Reed | Carl Reed & Associates | Individual
| Deane Kensok | Esri | Principal
|===

=== Conveners

Amy Rose, Overture Maps Foundation

== References

https://overturemaps.org/blog/2025/understanding-overtures-global-entity-reference-system/[Understanding GERS]

= Annex A: Precisely GERS implementation

*Date of most recent version:*

June 2025

*Implementation description:*

Precisely, a global leader in data integrity with over 12,000 customers, including 93 of the Fortune 100, has integrated Overture Maps’ Global Entity Reference System (GERS) into their https://www.precisely.com/solution/data-link?utm_source=Overture&utm_medium=Case+Study&utm_id=GERS[Data Link program]. Data Link streamlines integrating datasets from multiple providers by connecting data from Precisely and other organizations via unique identifier systems. The connection Data Link establishes between GERS and Precisely’s unique IDs dramatically reduces the time and cost of integrating Overture Maps’ standardized and interoperable datasets with Precisely’s comprehensive data portfolio spanning properties, locations, markets, and more.

Precisely solutions leverage their broader ID system and the PreciselyID, a unique and persistent identifier assigned to addresses through validation and geocoding services. By creating link tables between GERS IDs and Precisely’s unique IDs, they’ve eliminated the need for complex spatial operations.

*Implementation URL:*

https://www.precisely.com/solution/data-link?utm_source=Overture&utm_medium=Case+Study&utm_id=GERS

*Is implementation complete?*

* [x] Yes
