
[abstract]
== Abstract

The document provides the GERS Community Standard Justification Document submission team's responses to comments received during the public comment period. A number of the comments desired clarification on several issues. These are summarized below:

1. Is there a requirement to use the Overture Maps GERS implementation? No. The GERS Model and Framework defined in the Community Standard is technology and vendor neutral. There are zero dependencies on using the Overture implementation. Decisions as to whether to work with Overture and use their framework and tools or whether an organization wishes to implement the entire or components of the model/framework internally is based on the organizations requirements for geospatial data integration and sharing.
2. Does implementing the Community Standard require the use of OMF tools and workflows? No.
3. Does the GERS identifier replace existing feature identifiers? No. GERS identifiers are designed to work in collaboration with existing feature identifiers with the goal of enhancing the ability to integrate/join/share geospatial content across disparate geospatial datasets.
4. Does implementing the Community Standard require using the OMF conflation tools? No. How conflation functions are performed and what conflation tools could be used is not part of the Community Standard. Such decisions are up to the organization that wishes to implement/use the GERS model/framework.
5. Is the GERS Community Standard an implementation standard? No, the GERS Community Standard defines a logical model and framework that can be implemented by any organization, either in its entirety or as components. The OGC has defined numerous conceptual and logical models such as https://www.ogc.org/standards/citygml/[CityGML 3.0] and the https://docs.ogc.org/as/19-014r3/19-014r3.html[Core Tiling Conceptual and Logical Models for 2D Euclidean Space]. Further, there are a number of OGC Community Standards that defined models that can be implemented. These include 3D Tiles and I3S.




== Preface

The Global Entity Reference System (GERS) model and framework defines an approach for assigning and cataloguing persistent, unique, open, and interoperable identifiers to real-world geospatial entities to support consistent reference and integration across datasets from multiple providers and jurisdictions. However, the GERS model does not restrict the use of other identifiers such as those already established in deployed geospatial datasets. As part of the OGC Community Standrd Process, a public comment period is required. The GERS Justification document comment period completed March 3, 2026. All comments were submitted and archived in an OGC GitHub repository.

== Security considerations

No security considerations have been made for this document.

== Submitters

All questions regarding this document should be directed to the editor or the editors or the OGC:

|===
|*Name* |*Affiliation*
| |
|===
