== Detailed Responses to Comments

=== Comment

`Is the OGC is proposing the 'GERS Community Standard' to encourage map providers to "be 100% consistent with the existing Overture Maps Foundation reference map"?`

No. Please see comment summary in above <<abstract,Abstract>>

=== Comment

`I thus propose to retitled this proposal as "Select Overture as unique and single UUID for geospatial objets" to make thing clear for everybody.`

Nowhere in the CS Justification Document is there a statement requiring the use of OMF identifiers they have generated. Any organization can, based on their requirements and use cases, decide to implement their own GERS framework or they can choose to work with OMF or they can pursue some hybrid solution.

=== Comment

`The purpose of any developed standard is to provide "unique, open, and interoperable identifiers" (s. 2). This, by necessity, requires a central assignment authority.`

No, a global central assignment authority such as IANA is not required. Any organization implementing the GERS Model/framework could/should be the authority for their organization. 

=== Comment

`The document they are proposing to review sets the Overture Map foundation as the sole source.`

No. Please see comment summary in above <<abstract,Abstract>>

=== Comment

`I do see a potential overlap with the proposed OPN SWG, as stated in a previous comment.`

Possibly, although there is a greater potential for synergy. Check out the OGC Member https://regrid.com/blog/introducing-enhanced-land-use-insights-through-the-regrid-id-and-overture-maps-foundations-gers-id-matchst-title-here[REGRID's] use of the GERS framework to enrich and augment their parcel map data holdings. From the REGRID/Overture presse release: "We’re excited to announce a new interoperable ID match into our parcel data offering: a direct linkage delivered via a data bridge between our stable, persistent UUID - the Regrid ID and the GERS ID from the Overture Maps Foundation’s Places (Points-of-Interest) dataset".

=== Comment

`Assignment of IDs is the core purpose of the standard.`

This is an incorrect assumption. The goal of the GERS Model and framework is to simplify data integration and sharing across different datasets and platforms, fostering collaboration and innovation in the geospatial industry. How the unique ID is generated is only one aspect of the overall model and framework.

=== Comment

`Overture wishes to becomes the source of unique identifiers at the cost of distorting the standards process.`

This is an incorrect assumption. First, the Community Standard does not mandate the use of the Overture Maps implementation. Second, the Community Standard nowhere states the requirement to only use IDs generated by Overture Maps. As such, any organization that implements the GERS Model and framework can:

- Use existing OMF IDs if they desire.
- Generate their own feature IDs by following the ID generation requirements stated in Community Standard. Useful in a classified environment in which links to external sources may not be possible
- They can cross link existing internal feature IDs with GERS compliant IDs from other GERS framework implementations (See REGRID example).
- And other variations.

As another example, consider the https://overturemaps.org/case-study/2025/precisely-accelerates-data-integration-with-overture-gers-ids/[Precisely] implementation: Precisely, a global leader in data integrity with over 12,000 customers, including 93 of the Fortune 100, has integrated Overture Maps’ Global Entity Reference System (GERS) into their Data Link program. Data Link streamlines integrating datasets from multiple providers by connecting data from Precisely and other organizations via unique identifier systems. 

