== Detailed Responses to Comments

=== Comment - Stefan Keller and suggested by others

`Is the OGC is proposing the 'GERS Community Standard' to encourage map providers to "be 100% consistent with the existing Overture Maps Foundation reference map"?`

No. Please see comment summary in above <<abstract,Abstract>>

=== Comment - Christian Quest

`I thus propose to retitled this proposal as "Select Overture as unique and single UUID for geospatial objets" to make thing clear for everybody.`

Nowhere in the CS Justification Document is there a statement requiring the use of OMF identifiers they have generated. Any organization can, based on their requirements and use cases, decide to implement their own GERS framework or they can choose to work with OMF or they can pursue some hybrid solution.

=== Comment - Paul Norman

`The purpose of any developed standard is to provide "unique, open, and interoperable identifiers" (s. 2). This, by necessity, requires a central assignment authority.`

No, a global central assignment authority such as IANA is not required. Any organization implementing the GERS Model/framework could/should be the authority for their organization. 

=== Comment - 

`The document they are proposing to review sets the Overture Map foundation as the sole source.`

No. Please see comment summary in above <<abstract,Abstract>>

=== Comment - Linda van den Brink

`I do see a potential overlap with the proposed OPN SWG, as stated in a previous comment.`

Possibly, although there is a greater potential for synergy. Check out the OGC Member https://regrid.com/blog/introducing-enhanced-land-use-insights-through-the-regrid-id-and-overture-maps-foundations-gers-id-matchst-title-here[REGRID's] use of the GERS framework to enrich and augment their parcel map data holdings. From the REGRID/Overture presse release: "We’re excited to announce a new interoperable ID match into our parcel data offering: a direct linkage delivered via a data bridge between our stable, persistent UUID - the Regrid ID and the GERS ID from the Overture Maps Foundation’s Places (Points-of-Interest) dataset".

=== Comment - Paul Norman

`Assignment of IDs is the core purpose of the standard.`

This is an incorrect assumption. The goal of the GERS Model and framework is to simplify data integration and sharing across different datasets and platforms, fostering collaboration and innovation in the geospatial industry. How the unique ID is generated is only one aspect of the overall model and framework.

=== Comment - Paul Norman

`Overture wishes to becomes the source of unique identifiers at the cost of distorting the standards process.`

This is an incorrect assumption. First, the Community Standard does not mandate the use of the Overture Maps implementation. Second, the Community Standard nowhere states the requirement to only use IDs generated by Overture Maps. As such, any organization that implements the GERS Model and framework can:

- Use existing OMF IDs if they desire.
- Generate their own feature IDs by following the ID generation requirements stated in Community Standard. Useful in a classified environment in which links to external sources may not be possible
- They can cross link existing internal feature IDs with GERS compliant IDs from other GERS framework implementations (See REGRID example).
- And other variations.

As another example, consider the https://overturemaps.org/case-study/2025/precisely-accelerates-data-integration-with-overture-gers-ids/[Precisely] implementation: Precisely, a global leader in data integrity with over 12,000 customers, including 93 of the Fortune 100, has integrated Overture Maps’ Global Entity Reference System (GERS) into their Data Link program. Data Link streamlines integrating datasets from multiple providers by connecting data from Precisely and other organizations via unique identifier systems. 

=== Comment - Paul Norman and Simon Poole.

`As has been pointed out the OMF is a pay-to-play organisation under the control of a small number of larger organisation in the tech space. There do not seem to be any structures that would allow public oversight and control nor any published documentation that would give insight to its business in any form.`

From one of the supporters of the OMF GERS submission to the OGC: We believe that advancing GERS through the OGC standards process is the right path. The governance, transparency, and technical rigor provided by OGC are essential for broad adoption and long-term stewardship. Elevating GERS to an OGC Community Standard will strengthen the geospatial ecosystem as a whole and provide a foundation that benefits both data producers and consumers.

To be clear, Overture Maps is not "pay-to-play" in the sense of requiring a subscription or purchase fee to access its data. It is an open-data project aimed at providing free, open-source mapping data. Yes, to particpate in the ongoing technical specification of the model and framework, an organization does have to be a member. However, qualified nonprofit organizations and government entities may be eligible for exemption from the Linux Foundation Silver membership requirement. Just about every Standards Development Organization is pay-to-play in some form - even the IETF in the form of meeting regsitration fees.

=== Comment by Rock Miller

`I don't see this project being successful without deep integration of the time dimension. Geographic entities reconstruct themselves continuously over time, both spatially and semantically.`

There is no disagreement that time is highly relevant. The Community Standard does address the ability for tracking changes to a feature over time. This includes date time stamps as metadata for when a feature changes. This metadtaa is contained in the ChangeLog file. However, this capability does not address the broader use of time as suggested in this comment. At this time, such expansion of the temporal aspects of the model and framework are beyond the scope of the current activity.

=== Comment by KristoferGa 

`I have not made any detailed research on GERS, but before adopting it as a community standard, I would like to see more information about how this is supposed to work without a single registry. I don't think everyone will be able to use Overture's registry. And besides, non-public data will be shared among organisations that also needs persistent identifiers for real world entities. How is this solved?`

The GERS Model and Framework provides the ability to implement and use distributed Registries of unique IDs. This can be done using a Registry File and one or more Bridge Files. The Registry File contains all of the unique GERS IDs for a given implementation. The Registry File also contains links (URIs) to feature instances in a Reference Map (which may also be the source map data!). The Bridge Files capture information on how feature instances in a Registry File can be cross linked to the source feature instance. This is how REGRID and ESRI have implemented their use of the GERS Framework.

=== Comment by Morten Lindegaard

`However, there may then be an increased need to declare if identifiers are from authoritative governmental registers or not. Especially when identifiers syntactically look the same but come from different systems.`

=== Comment - Stefan Keller

`The GERS ID was developed by Overture Maps Foundation (OMF) to link the geodata of OM stakeholders internally. And the GERS ID seems to fulfill this function well. Now OMF seems to try to make GERS ID the “community standard” with OMF geodata at the centre, and infrastructure operated solely by OMF (not open source!).`

Again, wrong assumptions. Please see previous responses to this stated concern.

=== Comment by OpenStreetMap Foundation Board of Directors via Minh Nguyễn

We appreciate OSM's detailed response to the GERs Community Standard proposal. 

First, OSM (and others) state: Two Different Ideas About Geographic Truth. There is no disagrement with that statement. However, the draft CS and the justification make no statements regarding the physical geospatial content, such as how it is collected, its provenance, or its licensing. While valid issues, these are beyond the scope of the proposed model and framework.

Second, OSM states, "The OGC proposal states that a GERS Registry will be the single source of truth for all entities within an implementation. What the proposal does not address is the consequence for everything Overture chooses not to include." Neither the justification nor the draft CS make such statements. Neither the justification nor the draft CS states that any implementing organization must use the OMF implementation. Obviously, they can if they wish to. Further, yes, a GERS registry is the "source of truth" for GERS IDs any implementation of the framework may generate. However, the GERS IDs do nor replace or supercede any existing IDs used in any existing geospatial data repositories. The GERS IDs and associated registries are meant to enhance existing geospatial data repositories and enhance the ability to integrate and join resources.

Third, the OSM response states: "The standard should explicitly support the existence of multiple independent GERS-compatible registries, not just as a theoretical option but as a real design requirement. As currently written, the proposal is closely tied to the Overture implementation and its governance structures." Totally agree. Will reword the draft CS to make sure that these two requirements are clearly expressed.

=== Comment Foursquare

`Issue 1: The Matching Process Is Opaque and Non-Reproducible.` Neither the justification nor the draft CS makes any statement regarding how an organization should (or does) feature matching and/or conflation. That is outside the scope of the proposed CS.

`Issue 2: The Standard Does Not Define How New Entities Enter the System.` Such governance issues are beyond the scope of the proposed CS.

`Issue 3: Identifier Persistence Does Not Address Data Quality.` Data quality is out of the scope for the proposed CS. However, the wording referenced in the justification document has been chnaged to ". . . helping to improve data traceability, auditability, and accuracy." 

`Issue 4: The Standard Cannot Be Implemented Independently of Overture.` As defined in the draft CS, the requirements stated in the draft can be implemented independent of the Overture implementation. For example, the OGC CDB SWG is looking to define how to use the model/framework in a CDB datastore. The CDB standard is widely implemented by multiple, independent industry contractors for end-user simulation and mission rehearsal customers. This user base has asked for enhancements to theCDB Standard. In the case of CDB, the reference map is the CDB datastore. As to OGC APIs, an implementation of OGC API - Features could easily implemented for accessing existing reference maps.




