[obligation=normative]

== GERS Framework Requirements Classes

This Clause defines requirements classes with a standardization target of an implementation of the GERS Model and framework. Specifically, requirements defined in this clause are focused on the elements of the model required or recommended to implement a GERS framework consistent with the existing GERS implementation community. This clause does not define requirements for conflation, work flows, or storage/processing technologies.

=== Summary of GERS Framework Requirements Classes

The following table lists the mandatory and optional requirements classes for an implementation of the GERS Framework.

|===
| *Requirements class* | Description | Optional/Conditional/mandatory
| <<req-class-crs,requirements_class-gers-crs>> | Requirements for Coordinate Reference SYstems | Conditional
| <<req-class-id,requirements_class-gers-id>>  | Requirements for generation of a GERS ID      | Mandatory
| <<req-class-bridge,requirements_class-gers-bridge>> | Requirements for Bridge Files              | Mandatory
| <<req-class-registry,requirements_class-gers-registry>> | Requirements for the Registry File       | Optional
|===

NOTE: A complete implementation of the GERS framework requires implementation of all of the above requirements classes

=== General requirements

The following requirements class and recommendations specify "global" requirements pertinent to all schema, formats and so on used in an implementation of the GERS framework. Examples include the specification of language for properties of a name, specification of a bounding box, and time.

include::../requirements/requirements_class-gers-general.adoc[]

==== Recommended Schema Conventions

The following recommendations for schema conventions are suggested so that any new implementations of the GERS Framework and Model are consistent with all current (2026) implementation instances.

include::../recommendations/REC001-schema.adoc[]

==== Names recommendation

https://docs.overturemaps.org/schema/concepts/names/

==== Bounding Box recommendation

GeoJSON: The value of the bbox member MUST be an array of
   length 2*n where n is the number of dimensions represented in the
   contained geometries, with all axes of the most southwesterly point
   followed by all axes of the more northeasterly point.  The axes order
   of a bbox follows the axes order of geometries.


[[req-gers-time]]

==== Date Time recommendation

The following is the requirement for expressing date and time in any GERS implementation, regardless of these, type, pr schema. This requirement is consistent with various OGC and ISO standards as well as with STAC.

2024-10-15T00:00:00.000Z

[[req-class-crs]]

=== Requirement Class Coordinate Reference System (Conditional)

The CRS Requirements Class states that all coordinates used in any geometry, query, tiling scheme, and so on in an implementation of the GERS framework and model must be in the same (consistent) coordinate reference system.

NOTE: This requirements class is based on and is consistent with the CDB 2.0 and OGC API - Common CRS Requirements Classes.

include::../requirements/requirements_class-gers-crs.adoc[]

==== Requirement 1: CRS definition

The following requirement states that any metadata used in a GERS implementation be consistent with OGC Abstract Specification Topic 2: Referencing by coordinates (ISO 19111:2019).

include::../requirements/REQ001-crs-topic2.adoc[]

==== Requirement 2: Use same CRS Throughout

The following requirement states that any implementatin of the GERS Framework compliant with this community standard specifies only one CRS. This requirement ensures that rigorous coordinate transformations as stated in OGC Topic 2 can be successfully performed without loss of data.

include::../requirements/REQ002-crs-storage.adoc[]

==== Requirement 3: Valid CRS

The following requirement states that only no-projected coordinate reference systems are used in an implementaiton of the GERS framework. The are several reasons for this requirement, one of which is the possible use of global tiled storage systems for a GERS reference map.

include::../requirements/REQ003-crs-valid.adoc[]

==== Recommendation 1

In order to be consistent and compatible with existing GERS framework implementations (as of 2026), the following recommendation states that a WGS84 2d CRS be used. Further, if a CRS is not specified then the default is WGS84 2d with axis order longitude/latitude. This is known as OGC CRS84.

include::../recommendations/REC002-CRS.adoc[]

[[req-class-id]]
=== Requirements Class GERS ID (Mandatory)

As of the June 2025 release of the GERS schema and model, all GERS IDs are UUIDs: 128-bit, randomly-generated identifiers (https://www.rfc-editor.org/rfc/rfc9562.html#name-uuid-version-4[UUID v4]) that are kept stable across data releases and updates. These IDs are stored as strings with dashes: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx . UUID v4 is meant for generating UUIDs from truly random or pseudorandom numbers.

NOTE: This community standard does not specify how the GERS ID is generated. This is up to the organization implementing the GERS framework/model. The following requirements also do not preclude the organization from using an existing GERS implementation, such as from Overture Maps, as the source of a GERS ID. 

The following is the GERS ID Requirements Class

include::../requirements/requirements_class-gers-id.adoc[]

==== Every GERS entiry has a GERS ID

The following requirement states that every entity in a GER compliant implementation has a unique ID

include::../requirements/REQ004-must-have-id.adoc[]

==== ID is generated using UUID v4

The following requirement states that a GERS ID is generated using the rules as defined in UUID v4

include::../requirements/REQ005-id-uuid.adoc[]

[[req-class-bridge]]

=== Requirements Class Bridge Files

Bridge files connect GERS IDs to the feature IDs used in the source data. These files are a key component of a GERS implementation and offer two critical capabilities: Reverse lookup of source features and insight into the conflation process used. Bridge files should be updated whenever GERS content is updated with new, changed, ot deleted source data.

include::../requirements/requirements-class-gers-bridge.adoc[]

The bridge file schema consists of the following columns:

|===
|Column	| Data type	| Description
|id	| string |	A feature's GERS ID and is populated from the id column in the data schema
|record_id	| string	| The ID (identifier) of the feature in the source data provider (e.g. n2757802019@9) and is populated by parsing the `sources` column in the data schema.
|update_time	| string	| Represents the time the feature or dataset was updated, depending on the data provider. Populated by parsing the `sources` column in the Overture schema.
|dataset	| string	| Represents the name of the dataset the feature was provided in. Populated by parsing the `sources` column in the primary data schema.
|theme	| string |	Represents the theme the feature is a part of, provided by the creator of the bridge file itself.
|type	| string	| Represents the type of the feature, either derived from the data or provided by the creator of the bridge file.
|between	| array	| Represents the portion of the normalized length of the GERS feature the dataset way takes, represented by a range between 0 and 1.
|dataset_between	| array	| Represents the portion of the normalized length of the dataset way the GERS feature takes, represented by a range between 0 and 1.
|===

[[req-class-registry]]

=== Requirements Class Registry (Optional)

With each data update, the GERS Registry is also updated. A data update could be the inclusion of a new geospatial data source or an update to an existing geospatial data source. The GERS Registry serves as the single source of truth for all entities that are part of a GERS implementation. It serves as a comprehensive catalog that tracks every stable ID ever published across all data updates in an implementation of the GERS framework.

If an implementation of the GERS framework requires a Registry, then the following requirements class is mandatory.

include::../requirements/requirements-class-gers-registry.adoc[]

|===
|Column	| Data type	| Description
|id	| string	| GERS identifier (UUID)
|version	| integer	| Current version of the feature, incremented in each Overture release where the geometry or attributes of this feature changed.
|first_seen	| string	| GERS release when entity first appeared in the GERS repository
|last_seen	| string	| Most recent GERS release containing entity/feature
|last_changed	| string	| Last GERS release in which the entity/feature was changed, sourced from ChangeLog
|path	| string	| Relative path to entity/feature in release data (ReferenceMap?)
|bbox	| struct(xmin float, xmax float, ymin float, ymax float)	| Bounding box coordinates in the CRS of the GERS implementation.
|===

NOTE: The GERS Registry can be used to verify that an entity exists in Overture, track the history of that entity, and find new entities that have been added.
