== Terms and definitions

This document uses the terms defined in OGC Policy Directive 49, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== GERS Framework

a framework for structuring, discovering, and matching data across systems via the GERS ID. 

NOTE: The GERS framework is made up of several components – Reference Map, Changelogs, Registry, and Bridge Files.

=== GERS ID

a globally unique entity ID generated using the UUID (Universally Unique Identifier) format

[.source]
<<ISO19101-1>>

=== Source data

External geospatial data repository for which GERS IDs have been generated and corresponding entries/updates incorporated into the GERS Registry, Bridge Files, ChangeLog, and Reference Map. Open STreet Map is an example of an external repository.
