== GERS Framework Requirements Clasess

This Clause defines requirements classes with a standardization target of an implementation of the GERS Model. Specifically, requirements defined in this clause are focused on the elements of the model required to implement the GERS model. This clause does not define requirements for conflation, work flows, or storage/processing technologies.

=== Requirement Class Coordinate Reference System

The CRS Requriements Class states that all coordinates used in any geometry, query, tiling scheme, and so on in an implementation of the GERS model must be in the same (consistent) coordinate reference system.

NOTE: This requirements class is identical (except for informative wording) to the CDB 2.0 CRS Requirements Class.

Use the following table for Requirements Classes.

include::../requirements/requirements_class.adoc[]

==== Requirement 1

Paragraph - intro text for the requirement.

Use the following table for Requirements, number sequentially.

include::../requirements/requirement001.adoc[]

Dictionary tables for requirements can be added as necessary. Modify the following example as needed.

[width="90%",options="header"]
|===
|Names |Definition |Data types and values |Multiplicity and use
|name 1 |definition of name 1 |float |One or more (mandatory)
|name 2 |definition of name 2 |character string type, not empty |Zero or one (optional)
|name 3 |definition of name 3 |GML:: Point PropertyType |One (mandatory)
|===


==== Requirement 2

Paragraph - intro text for the requirement.

Use the following table for Requirements, number sequentially.

include::../requirements/requirement002.adoc[]
