[obligation=normative]

== GERS Framework Requirements Classes

This Clause defines requirements classes with a standardization target of an implementation of the GERS Model and framework. Specifically, requirements defined in this clause are focused on the elements of the model required to implement a GERS framework consistent with the existing GERS implementation community. This clause does not define requirements for conflation, work flows, or storage/processing technologies.

=== Requirement Class Coordinate Reference System

The CRS Requirements Class states that all coordinates used in any geometry, query, tiling scheme, and so on in an implementation of the GERS framework and model must be in the same (consistent) coordinate reference system.

NOTE: This requirements class is based on and is consistent with the CDB 2.0 and OGC API - Common CRS Requirements Classes.

include::../requirements/requirements_class-gers-crs.adoc[]

==== Requirement 1: CRS definition

The following requirement states that any metadata used in a GERS implementation be consistent with OGC Abstract Specification Topic 2: Referencing by coordinates (ISO 19111:2019).

include::../requirements/REQ001-crs-topic2.adoc[]

==== Requirement 2: Use same CRS Throughout

The following requirement states that any implementatin of the GERS Framework compliant with this community standard specifies only one CRS. This requirement ensures that rigorous coordinate transformations as stated in OGC Topic 2 can be successfully performed without loss of data.

include::../requirements/REQ002-crs-storage.adoc[]

==== Requirement 3: Valid CRS

The following requirement states that only no-projected coordinate reference systems are used in an implementaiton of the GERS framework. The are several reasons for this requirement, one of which is the possible use of global tiled storage systems for a GERS reference map.

include::../requirements/REQ003-crs-valid.adoc[]

==== Recommendation 1

In order to be consistent and compatible with existing GERS framework implementations, the following recommendation states that a WGS84 2d CRS be used. Further, if a CRS is not specified then the default is WGS84 2d with axis order longitude/latitude. This is known as OGC CRS84.

|===
|*Recommendation* | */rec/crs-definition* +
Coordinates - such as for geometry - in an implementation of the GERS framework _SHOULD_ be expressed using WGS-84 (World Geodetic System 1984), equivalent to https://spatialreference.org/ref/ogc/CRS84/[OGC CRS 84]. This is equivalent to EPSG (European Petroleum Survey Group) code 4326 (2 dimensions) but with axis order longtidude/latitude. If a geographic location also has a height or depth, the height or depth _SHOULD_ be expressed relative to the WGS-84 reference ellipsoid.

NOTE: The above recommendation is for backwards compatibility with existing GERS framework implementations.
|===

=== Requirements Class GERS ID

As of the June 2025 release, all GERS IDs are UUIDs: 128-bit, randomly-generated identifiers (https://www.rfc-editor.org/rfc/rfc9562.html#name-uuid-version-4[UUID v4]) that are kept stable across data releases and updates. These IDs are stored as strings with dashes: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx . UUID v4 is meant for generating UUIDs from truly random or pseudorandom numbers.

The following is the GERS ID Requirements Class

include::../requirements/requirements_class-gers-id.adoc[]

=== Requirements Class Bridge Files

Bridge files connect GERS IDs to the feature IDs used in the source data. These files are a key component of GERS and offer two critical capabilities: reverse lookup of source features and insight into the conflation process used. Bridge files should be updated whenever GERS content is updated with new, changed, ot deleted source data.

Dictionary tables for requirements can be added as necessary. Modify the following example as needed.

[width="90%",options="header"]
|===
|Names |Definition |Data types and values |Multiplicity and use
|name 1 |definition of name 1 |float |One or more (mandatory)
|name 2 |definition of name 2 |character string type, not empty |Zero or one (optional)
|name 3 |definition of name 3 |GML:: Point PropertyType |One (mandatory)
|===

