[preface]

== Preface

The OGC Global Entity Reference System Standard (GERS) defines:

. A reference system for exchanging and enriching geospatial data.
. A schema to structure geospatial data into a datastore that includes the GERS id and that is consistent with other OGC/ISO Standards.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[abstract]
== Abstract

GERS was developed by the https://overturemaps.org/[Overture Maps Foundation] and launched in June 2025 as a way to provide unique, open, 
and interoperable identifiers for geospatial entities such as buildings, places, and road segments. The GERS framework also provides schema and a framework
to register and maintain a persistent registry of these unique IDs. This includes a change log so that changes to
geographic entities over time can be captured and persisted. This system aims to simplify data integration and sharing across different 
datasets and platforms, fostering collaboration and innovation in the geospatial industry.

The OGC GERS Standard focuses on:

* The model as documented in the current Overture data and registry schema, 
* The generation of GERS IDs, a unique identifier for real-world geospatial entities across data releases and maintains consistency when the same entity appears in multiple source datasets..
* BridgeFiles: Bridge files connect the unique GERS IDs to the features identifiers used in the source data. These files are a key component of GERS and 
offer two critical capabilities: reverse lookup of source features and the ability to join content from multipoe geospatial data repositories.
* ChangeLog: A GERS changelog capture changes in the map data from the previous release to the current release. This information can be used to 
guide decisions about data matching, better understand data stability, and help detect data errors.
* ReferenceMap: A reference map of all entities that have been assigned a unique GERS ID. The content in the reference map datastore is defined by a set of JSON schema.
* Registry: A GERS Registry serves as the single source of truth for all entities that are part of an implementation of a Global Entity Reference System.
* JSON Schema: The format of the content stored in the reference map is defined using JSON schema. Overture releases their reference map data as GeoParquet. 
GeoJSON is used as the default canonical geospatial format. GeoJSON provides a "mental model and language" to express data constructions in the schema. 
The OGC GERS Standard schema reference docs will describe key schema concepts for each theme and definitions and examples for each feature type.
* Feature Types: The source Overture JSON schema provide type enumerations for the base themes, such as land cover types. The OGC GERS Standard will 
define how an enumeration contained in the schema can be extended while maintaining backwards compatibility.

Each of the above components are defined using JSON Schema that will clearly and fully documented in the draft OGC GERS Standard. 

This focus that any implementation 
by any organization that will be 100% consistent with the existing Overture foundation map but "owned" by the implementing organization. An example of this 
approach is the `precisely` implementation (See Annex D).

== Security considerations

   Do not assume that the GERS IDs (UUIDs) are hard to guess. For example the IDs should not be used
   as security capabilities (identifiers whose mere possession grants
   access).  A predictable random number source will exacerbate the situation.

   Do not assume that it is easy to determine if a GERS ID has been
   slightly transposed in order to redirect a reference to another
   object.  Humans do not have the ability to easily check the integrity
   of a GERS ID by simply glancing at it.

NOTE: The security measures discussed above to not provide confentiality. This is outside the scope of this document.

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

|===
|*Name* |*Affiliation*
| Carl Reed | Carl Reed & Associates
|===

== Contributors

//This clause is optional.

Additional contributors to this Standard include the following:

Individual name(s), Organization

