== Terms and definitions

This document uses the terms defined in OGC Policy Directive 49, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== feature identifier

identifier that uniquely designates a feature instance

[SOURCE: ISO 19142:2010]

NOTE: In the GERS Framework, the feature ID is the unique ID used for a feature instance in a source dataset (see source data). Further, the generated ID is not meant to replace any existing feature IDs used in the source data

=== feature instance

individual of a given feature type having specified feature attribute values (see entity)

[SOURCE: ISO 19101-1:2014]

=== feature type (see type)

class of features having common characteristics 

SOURCE: ISO 19156:2023] 

=== geographic feature

representation of real world phenomenon associated with a location relative to the Earth

[SOURCE: ISO 19101-2:2018]

=== Bridge Files

bridge files connect GERS IDs to the IDs contained in the source data. 

NOTE: These files are a key component of an implementation of the Framework and offer two critical capabilities: reverse lookup of source features and insight into any conflation process used to process source feature.

=== ChangeLog

a changelog documents/captures changes in the data from the previous release to the current release of a reference map. 

NOTE: This information can be used to guide decisions about data matching, better understand data stability, and help detect data errors.

=== Entity (feature)

refers to a physical feature such as a building, address, or road segment. 

=== GERS Framework

a framework for generating, structuring, discovering, and matching data across systems via the unique IDs. 

NOTE: The Framework is made up of several components – Reference Map, Changelogs, Registry, and Bridge Files.

=== ID

a globally unique entity ID generated using the IETF UUID (Universally Unique Identifier) format

[.source]
<<ISO19101-1>>

=== GERS Reference Map

validated map datasets that connect the IDs to real-world entities.

=== Registry

a Registry serves as the single source of truth for all entities that are registered with and part of a Global Entity Reference System framework implementation. 

NOTE: The Registry is a comprehensive catalog that tracks every stable ID ever published across all data releases in a given implementation of the Framework.

=== Themes

geographic feature types for which schema and rules have been documented for inclusion in an implementation of an implmentation of the Framework. 

=== theme

a specific set of related geographic features such as streets, buildings, or rivers that share common feature types

=== type (feature type)

class of features having common characteristics

=== Source data

external geospatial data repository for which the unique IDs were generated and corresponding entries/updates incorporated into the GERS Registry, Bridge Files, ChangeLog, and Reference Map. Open Street Map is an example of an external geospatial repository.
