[obligation=normative]

== GERS Framework Requirements Classes

This Clause defines requirements classes with a standardization target of an implementation of the GERS Model and framework. Specifically, requirements defined in this clause are focused on the elements of the model required or recommended to implement a GERS framework consistent with the existing GERS implementation community. This clause does not define requirements for conflation, work flows, or storage/processing technologies.

=== General requirements

The following requirements class specifies "global" requirements pertinent to all schema, formats and so on used in an implementation of the GERS framework. Examples include the specification of language for properties of a name, specification of a bounding box, and time.

==== Recommended Schema Conventions

The following recommendations for schema conventions are suggested so that any new implementations of the GERS Framework and Model are consistent with all current (2026) implementation instances.

include::../recommendations/REC001-schema.adoc[]

==== Names recommendation

https://docs.overturemaps.org/schema/concepts/names/

==== Bounding Box recommendation

GeoJSON: The value of the bbox member MUST be an array of
   length 2*n where n is the number of dimensions represented in the
   contained geometries, with all axes of the most southwesterly point
   followed by all axes of the more northeasterly point.  The axes order
   of a bbox follows the axes order of geometries.


==== Date Time recommendation

time

=== Requirement Class Coordinate Reference System

The CRS Requirements Class states that all coordinates used in any geometry, query, tiling scheme, and so on in an implementation of the GERS framework and model must be in the same (consistent) coordinate reference system.

NOTE: This requirements class is based on and is consistent with the CDB 2.0 and OGC API - Common CRS Requirements Classes.

include::../requirements/requirements_class-gers-crs.adoc[]

==== Requirement 1: CRS definition

The following requirement states that any metadata used in a GERS implementation be consistent with OGC Abstract Specification Topic 2: Referencing by coordinates (ISO 19111:2019).

include::../requirements/REQ001-crs-topic2.adoc[]

==== Requirement 2: Use same CRS Throughout

The following requirement states that any implementatin of the GERS Framework compliant with this community standard specifies only one CRS. This requirement ensures that rigorous coordinate transformations as stated in OGC Topic 2 can be successfully performed without loss of data.

include::../requirements/REQ002-crs-storage.adoc[]

==== Requirement 3: Valid CRS

The following requirement states that only no-projected coordinate reference systems are used in an implementaiton of the GERS framework. The are several reasons for this requirement, one of which is the possible use of global tiled storage systems for a GERS reference map.

include::../requirements/REQ003-crs-valid.adoc[]

==== Recommendation 1

In order to be consistent and compatible with existing GERS framework implementations (as of 2026), the following recommendation states that a WGS84 2d CRS be used. Further, if a CRS is not specified then the default is WGS84 2d with axis order longitude/latitude. This is known as OGC CRS84.

include::../recommendations/REC002-CRS.adoc[]

=== Requirements Class GERS ID (Mandatory)

As of the June 2025 release of the GERS schema and model, all GERS IDs are UUIDs: 128-bit, randomly-generated identifiers (https://www.rfc-editor.org/rfc/rfc9562.html#name-uuid-version-4[UUID v4]) that are kept stable across data releases and updates. These IDs are stored as strings with dashes: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx . UUID v4 is meant for generating UUIDs from truly random or pseudorandom numbers.

NOTE: This community standrd does not specify how the GERS ID is generated. This is up to the organization implementing the GERS framework/model. The following requirements also do not preclude the organization from using an existing GERS implementation, such as from Overture Maps, as the source of a GERS ID. 

The following is the GERS ID Requirements Class

include::../requirements/requirements_class-gers-id.adoc[]

==== Every GERS entiry has a GERS ID

The following requirement states that every entity in a GER compliant implementation has a unique ID

include::../requirements/REQ004-must-have-id.adoc[]

==== ID is generated using UUID v4

The following requirement states that a GERS ID is generated using the rules as defined in UUID v4

include::../requirements/REQ005-id-uuid.adoc[]

=== Requirements Class Registry (Optional)

With each data update, the GERS Registry is also updated. A data update could be the inclusion of a new geospatial data source or an update to an existing geospatial data source. The GERS Registry serves as the single source of truth for all entities that are part of a GERS implementation. It serves as a comprehensive catalog that tracks every stable ID ever published across all data updates in an implementation of the GERS framework.

If an implementation of the GERS framework requires a Registry, then the following requirements class is mandatory.

include::../requirements/requirements-class-gers-registry.adoc[]

=== Requirements Class Bridge Files

Bridge files connect GERS IDs to the feature IDs used in the source data. These files are a key component of GERS and offer two critical capabilities: reverse lookup of source features and insight into the conflation process used. Bridge files should be updated whenever GERS content is updated with new, changed, ot deleted source data.

Dictionary tables for requirements can be added as necessary. Modify the following example as needed.

[width="90%",options="header"]
|===
|Names |Definition |Data types and values |Multiplicity and use
|name 1 |definition of name 1 |float |One or more (mandatory)
|name 2 |definition of name 2 |character string type, not empty |Zero or one (optional)
|name 3 |definition of name 3 |GML:: Point PropertyType |One (mandatory)
|===

