[preface]

== Preface

The OGC Global Entity Reference System Standard (GERS) framework defines:

. A model and system for exchanging and enriching geospatial data.
. A services architecture comprised of components that can be implemented as an operational GERS frameowk.
. The schema to structure geospatial data into a datastore that includes the GERS id and that is consistent with other OGC/ISO Standards.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[abstract]
== Abstract

GERS was developed by the https://overturemaps.org/[Overture Maps Foundation] and launched in June 2025 as a way to provide unique, open, 
and interoperable identifiers for geospatial entities such as buildings, places, and road segments. The GERS framework also provides schema and a framework
to register and maintain a persistent registry of these unique IDs. This includes a change log so that changes to
geographic entities over time can be captured and persisted. This system aims to simplify data integration and sharing across different 
datasets and platforms, fostering collaboration and innovation in the geospatial industry.

== Security considerations

   Do not assume that the GERS IDs (UUIDs) are hard to guess. For example the IDs should not be used
   as security capabilities (identifiers whose mere possession grants
   access).  A predictable random number source will exacerbate the situation.

   Do not assume that it is easy to determine if a GERS ID has been
   slightly transposed in order to redirect a reference to another
   object.  Humans do not have the ability to easily check the integrity
   of a GERS ID by simply glancing at it.

NOTE: The security measures discussed above do not provide confidentiality. This is outside the scope of this document.

[.preface]
== Document editors

The following OGC Members participated in editing this document:

[%unnumbered]
|===
^h| Person ^h| Organization Represented
| Carl Reed | Carl Reed & Associates
|===

== Submitting organizations

The following OGC Member organizations support the CDB 2.0 Physical Materials Extension submission.

|===
|*Organization name*
| Overture Maps Foundation |
| Esri |
| Carl Reed & Associates |
|===

== Contributors

Additional contributors to this Standard include the following:

|===
|*Name* |*Affiliation*
| |
|===

[.preface]
== Future work

Improvements to this Standard will be made based on implementation and changing technical requirements. 
