[obligation=normative]

== GERS Framework Requirements Classes

This Clause defines requirements classes with a standardization target of an implementation of the GERS Model and framework. Specifically, requirements defined in this clause are focused on the elements of the model required or recommended to implement a GERS framework consistent with the existing GERS implementation community. This clause does not define requirements for conflation, work flows, or storage/processing technologies.

=== Summary of GERS Framework Requirements Classes

The following table lists the mandatory and optional requirements classes for an implementation of the GERS Framework.

|===
| *Requirements class* | Description | Optional/Conditional/mandatory
| <<req-gers-general,requirements_class-gers-general>> | General system wide requirements | Conditional
| <<req-class-crs,requirements_class-gers-crs>> | Requirements for Coordinate Reference SYstems | Conditional
| <<req-class-id,requirements_class-gers-id>>  | Requirements for generation of a GERS ID      | Mandatory
| <<req-class-bridge,requirements_class-gers-bridge>> | Requirements for Bridge Files              | Mandatory
| <<req-class-registry,requirements_class-gers-registry>> | Requirements for the Registry File       | Optional
|===

NOTE: A complete implementation of the GERS framework requires implementation of all of the above requirements classes

[[req-gers-general]]

=== General requirements and recommendations

The following requirements class and recommendations specify "global" requirements pertinent to all schema, formats and so on used in an implementation of the GERS framework. Examples include the specification of language for properties of a name, specification of a bounding box, and time.

include::../requirements/requirements_class-gers-general.adoc[]

[[rec-gers-schema]]

==== Recommended Schema Conventions

The following recommendations for schema conventions are suggested so that any new implementations of the GERS Framework and Model are consistent with all current (2026) implementation instances.

include::../recommendations/REC001-schema.adoc[]

==== Names recommendation

https://docs.overturemaps.org/schema/concepts/names/

[[req-gers-datetime]]

==== Date Time Requirement

The following is the requirement for expressing date and time in any GERS implementation, regardless of theme, type, or schema. This requirement is consistent with various OGC and ISO standards as well as with STAC.

include::../requirements/REQ001-gers-general-datetime.adoc[]

An example of  a datetime string that complies with REQ001 is: `2024-10-15T00:00:00.000Z`

[[req-gers-bbox]]

==== Bounding Box requirement

The following requirement defines how to express a bounding box in the CRS of an impementation of the GERS framework. 

include::../requirements/REQ002-gers-general-bbox.adoc[]

An example that follows  {'xmin': 80.67177, 'xmax': 80.67182, 'ymin': 26.619795, 'ymax': 26.619843}

[[req-class-crs]]

=== Requirement Class Coordinate Reference System (Conditional)

The CRS Requirements Class states that all coordinates used in any geometry, query, tiling scheme, and so on in an implementation of the GERS framework and model must be in the same (consistent) coordinate reference system.

NOTE: This requirements class is based on and is consistent with the CDB 2.0 and OGC API - Common CRS Requirements Classes.

include::../requirements/requirements_class-gers-crs.adoc[]

==== Requirement CRS definition

The following requirement states that any CRS metadata used in a GERS implementation be consistent with OGC Abstract Specification Topic 2: Referencing by coordinates (ISO 19111:2019).

include::../requirements/REQ004-crs-topic2.adoc[]

==== Requirement Use same CRS Throughout

The following requirement states that any implementation of the GERS Framework compliant with this community standard specifies only one CRS. This requirement ensures that rigorous coordinate transformations as stated in OGC Topic 2 can be successfully performed without loss of data.

include::../requirements/REQ005-crs-storage.adoc[]

==== Requirement Valid CRS

The following requirement states that only no-projected coordinate reference systems are used in an implementaiton of the GERS framework. The are several reasons for this requirement, one of which is the possible use of global tiled storage systems for a GERS reference map.

include::../requirements/REQ006-crs-valid.adoc[]

==== Recommendation 1

In order to be consistent and compatible with existing GERS framework implementations (as of 2026), the following recommendation states that a WGS84 2d CRS be used. Further, if a CRS is not specified then the default is WGS84 2d with axis order longitude/latitude. This is known as OGC CRS84.

include::../recommendations/REC002-CRS.adoc[]

[[req-class-id]]
=== Requirements Class GERS ID (Mandatory)

As of the June 2025 release of the GERS schema and model, all GERS IDs are UUIDs: 128-bit, randomly-generated identifiers (https://www.rfc-editor.org/rfc/rfc9562.html#name-uuid-version-4[UUID v4]) that are kept stable across data releases and updates. These IDs are stored as strings with dashes: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx . UUID v4 is meant for generating UUIDs from truly random or pseudorandom numbers.

NOTE: This community standard does not specify how the GERS ID is generated. This is up to the organization implementing the GERS framework/model. The following requirements also do not preclude the organization from using an existing GERS implementation, such as from Overture Maps, as the source of a GERS ID. 

The following is the GERS ID Requirements Class

include::../requirements/requirements_class-gers-id.adoc[]

==== Every GERS entiry has a GERS ID

The following requirement states that every entity in a GER compliant implementation has a unique ID

include::../requirements/REQ006-must-have-id.adoc[]

==== ID is generated using UUID v4

The following requirement states that a GERS ID is generated using the rules as defined in UUID v4

include::../requirements/REQ007-id-uuid.adoc[]

[[req-class-bridge]]

=== Requirements Class Bridge Files

Bridge files connect GERS IDs to the feature IDs used in the source data. These files are a key component of a GERS implementation and offer two critical capabilities: Reverse lookup of source features and insight into the conflation process used. Bridge files should be updated whenever GERS content is updated with new, changed, ot deleted source data.

include::../requirements/requirements-class-gers-bridge.adoc[]

==== Structure of the BridgeFile name

include::../requirements/REQ008-gers-bridgefile-name.adoc[]

==== BridgeFile Schema Content

include::../requirements/REQ009-gers-bridgefile-schema.adoc[]

The bridge file schema consists of the following columns:

|===
|Column	| Data type	| Description
|id	| string |	A feature's GERS ID and is populated from the id column in the data schema
|record_id	| string	| The ID (identifier) of the feature in the source data provider (e.g. n2757802019@9) and is populated by parsing the `sources` column in the data schema.
|update_time	| string	| The time the feature or dataset was updated, depending on the data provider. Populated by parsing the `sources` column in the Overture schema.
|dataset	| string	| The name of the source dataset in which the feature is contained. Populated by parsing the `sources` column in the primary data schema.
|theme	| string |	The theme the feature is a part of, provided by the creator of the bridge file itself.
|type	| string	| The type of the feature, either derived from the data or provided by the creator of the bridge file.
|between	| array	| The portion of the normalized length of the GERS feature the dataset way takes, represented by a range between 0 and 1.
|dataset_between	| array	| The portion of the normalized length of the dataset way the GERS feature takes, represented by a range between 0 and 1.
|===

NOTE: The `between` property is applicable to segments contained in a lineal feature dataset, such as Roads or Streams. The concept is similar to how a position on a linear segment is identified in a linear reference system.

==== Example of BridgeFile query

https://docs.overturemaps.org/gers/bridge-files/#example-examining-the-source-data-for-the-building-dataset[An example query of a bridge file maintained in the Overture Maps implementation]. This query assumes that the BridgeFile information is maintained in an S3 GeoParquet structured bucket.

[[req-class-registry]]

=== Requirements Class Registry (Optional)

With each data update, the GERS Registry is also updated. A data update could be the inclusion of a new geospatial data source or an update to an existing geospatial data source. The GERS Registry serves as the single source of truth for all entities that are part of a GERS implementation. It serves as a comprehensive catalog that tracks every stable ID ever published across all data updates in an implementation of the GERS framework.

If an implementation of the GERS framework requires a Registry, then the following requirements class is mandatory.

include::../requirements/requirements-class-gers-registry.adoc[]

==== GERS registry file name

The following requirement defines the name for a GERS regsitry file. Please note that this name can be included in a longer URI/URL path to the actual location of the regsitry file. 

include::../requirements/REQ010-gers-registry-name.adoc[]

==== Schema for GERS registry file

The following requirement states that using the registry schema defined in Table xyz below is mandatory.

include::../requirements/REQ011-gers-registry-schema.adoc[]

==== Updates to GERS registry file

The following requiremehnt defines the rules for how updates are performed on the GERS regsitry.

include::../requirements/REQ012-gers-registry-updates.adoc[]


|===
|Column	| Data type	| Description
|id	| string	| GERS identifier (UUID)
|version	| integer	| Current version of the feature, incremented in each release whenever the geometry or attributes of this feature changed.
|first_seen	| string	| GERS release number when entity first appeared in the GERS repository
|last_seen	| string	| Most recent GERS release containing entity/feature
|last_changed	| string	| Last GERS release in which the entity/feature was changed, sourced from ChangeLog
|path	| string	| Relative path to entity/feature in release data (ReferenceMap?)
|bbox	| struct(xmin float, xmax float, ymin float, ymax float)	| Bounding box coordinates in the CRS of the GERS framework implementation.
|===

NOTE: The GERS Registry can be used to verify that an entity exists in Overture, track the history of that entity, and find new entities that have been added.

==== Example query of a GERS Registry (From Overture)

You can use the GERS Registry to verify that an entity exists in the GERS framework data, track the history of that entity, and find new entities that have been added. For example, a user might ask, "Is fea28f69-7afa-460c-b270-61ef74cd340c part of GERS?" The user can query the GERS Registry to find out:

```
SELECT 
    *
FROM read_parquet('s3://overturemaps-us-west-2/registry/*.parquet')
WHERE id='fea28f69-7afa-460c-b270-61ef74cd340c';
```

The query response will show that fea28f69-7afa-460c-b270-61ef74cd340c is a building first released in the Overture GERS i9plementation in June 2025 and last seen in August 2025 (2025-08-20.1), the current release. The exact bounding box of the feature is {'xmin': 80.67177, 'xmax': 80.67182, 'ymin': 26.619795, 'ymax': 26.619843} and the relative path to the feature is /theme=buildings/type=building/part-00149-8a741876-e04d-4e66-bc96-0171910fa1b1-c000.zstd.parquet.

[[req-class-change-log]]

=== Requirements Class ChangeLog (Optional)

include::../requirements/requirements-class-gers-changelog.adoc[]
