[preface]

== Preface

The OGC Global Entity Reference System Standard defines:

. A reference system for exchanging and enriching geospatial data.
. A schema to structure geospatial data into a datastore that includes the GERS id and that is consistent with other OGC/ISO Standards.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[abstract]
== Abstract

<Insert Abstract Text here>

== Security considerations

   Do not assume that the GERS IDs (UUIDs) are hard to guess. For example the IDs should not be used
   as security capabilities (identifiers whose mere possession grants
   access).  A predictable random number source will exacerbate the situation.

   Do not assume that it is easy to determine if a GERS ID has been
   slightly transposed in order to redirect a reference to another
   object.  Humans do not have the ability to easily check the integrity
   of a GERS ID by simply glancing at it.

NOTE: The security measures discussed above to not provide confentiality. This is outside the scope of this document.

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

|===
|*Name* |*Affiliation*
| |
|===

== Contributors

//This clause is optional.

Additional contributors to this Standard include the following:

Individual name(s), Organization

