== Conventions

This sections provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.

=== Identifiers
The normative provisions in this standard are denoted by the URI

`http://www.opengis.net/spec/gers/`

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

All requirements that appear in this document are denoted by partial URIs which are relative to the namespace shown above.

For the sake of brevity, the use of “req” in a requirement URI denotes:

      `http://www.opengis.net/spec/gers/`

An example might be:

/req/registry/

All conformance tests that appear in this document are denoted by partial URIs which are relative to the namespace shown above.

For the sake of brevity, the use of “conf” in a requirement URI denotes:

        `http://www.opengis.net/spec/gers/`
